name: test
on: [push]

jobs:
  fmt:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: fmt
        uses: ./ci/image
        with:
          args: make -j fmt 

      - run: ./ci/scripts/files_changed.sh

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.39

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: test
        uses: ./ci/image
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODER_URL: ${{ secrets.CODER_URL }}
          CODER_EMAIL: ${{ secrets.CODER_EMAIL }}
          CODER_PASSWORD: ${{ secrets.CODER_PASSWORD }}
        with:
          args: make -j test/coverage

  bench:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/cache@v2
        with:
          path: ./cache
          key: ${{ runner.os }}-go-bench
          restore-keys: |
            ${{ runner.os }}-go-bench-

      - name: bench
        uses: ./ci/image
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODER_URL: ${{ secrets.CODER_URL }}
          CODER_EMAIL: ${{ secrets.CODER_EMAIL }}
          CODER_PASSWORD: ${{ secrets.CODER_PASSWORD }}
        with:
          args: sh -c "go test -bench=. cdr.dev/coder-cli/wsnet | tee output.txt"

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'go'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true

  gendocs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: generate-docs
        uses: ./ci/image
        with:
          args: make -j gendocs

      - run: ./ci/scripts/files_changed.sh
